controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
login_customer:
    path: '/customer/login'
    controller: App\Controller\CustomerLoginController::login
